remove nose dependancy
angr/claripy pull request #250
Opened 2021-11-18 20:13 UTC by Adersh97

2021-11-19 21:03 UTC, twizmwazin requested changes
Please take a look at the inline comments and the CI failures. Also, for future PRs, you may want to choose different branch names. The CI will use branches from other repos if their names match, so I presume some of the failures in this CI run are actually issues in the angr PR.

2021-11-19 21:03 UTC, twizmwazin commented on tests/test_vsa.py
> +    assert is_equal(si_concat, SI(bits=96, stride=1,                                                   lower_bound=0,                                                   upper_bound=0xfffffffffffffffff
Formatting

2021-11-19 21:03 UTC, twizmwazin commented on tests/test_vsa.py
> -    nose.tools.assert_true(claripy.backends.vsa.is_true(vsa_model(if_2.ite_excavated.args[1]) == vsa_model(VS(region='global', bits=32, val=0))))
Looks like everything was deleted from this point down?

2021-11-24 01:19 UTC, Adersh97 commented on tests/test_expression.py
> +            assert False, "`assert ast` should raise an exception"
I don't know if the test case always raises claripy.BackendError.

2021-11-24 01:32 UTC, rhelmot commented on tests/test_expression.py
> +            assert False, "`assert ast` should raise an exception"
They should always raise the error.

2021-11-24 01:42 UTC, Adersh97 commented on tests/test_expression.py
> +            assert False, "`assert ast` should raise an exception"
okay cool, I will use assertRaises then.

2022-05-18 05:04 UTC, twizmwazin commented
Closing in favor of #261

2022-05-18 05:04 UTC, closed without merging