Removed generators in test_merging.py
angr/claripy pull request #259
Opened 2022-03-04 03:43 UTC by mohitrpatil

2022-03-04 17:30 UTC, rhelmot approved these changes

2022-03-09 20:21 UTC, twizmwazin requested changes

2022-03-09 20:21 UTC, twizmwazin commented on tests/test_expression.py
> +#pylint: disable=no-self-use
Please put a space between the # and pylint. Additionally, these can be comma-seperated lists rather than multiple lines.

2022-03-09 20:21 UTC, twizmwazin commented on tests/test_expression.py
> +#pylint: disable=comparison-with-itself
This lint should be fixed, not ignored.

2022-03-09 20:21 UTC, twizmwazin commented on tests/test_solver.py
> +#pylint: disable=line-too-long
Please fix this rather than ignore it

2022-03-09 20:21 UTC, twizmwazin commented on tests/test_solver.py
> +#pylint: disable=raise-missing-from
Please fix this one too

2022-03-09 20:21 UTC, twizmwazin commented on tests/test_solver.py
> +class TestSolver(unittest.TestCase):
The test method names in this class can be improved. They're kinda redundant and not normalized to snake case. For example, `test_solver_solver_SolverHybrid` could probably become `test_solver_hybrid`.

2022-03-09 20:21 UTC, twizmwazin commented on tests/test_solver.py
>  solver_list = (claripy.Solver, claripy.SolverReplacement, claripy.SolverHybrid, claripy.SolverComposite, claripy.SolverCacheless)
This is unused now, yes?

2022-03-09 20:21 UTC, twizmwazin commented on tests/test_solver.py
> +        print(s.min(x, extra_constraints=[x >= 20]))
While we're here, these print statements could be removed.

2022-03-09 20:24 UTC, twizmwazin commented
As a general rule, I think ignoring `no-self-use` and `missing-class-docstring` are fine in test files, but other lint errors should be fixed rather than ignored.

2022-03-24 07:40 UTC, mohitrpatil commented on tests/test_solver.py
>  solver_list = (claripy.Solver, claripy.SolverReplacement, claripy.SolverHybrid, claripy.SolverComposite, claripy.SolverCacheless)
I removed it.

2022-03-24 23:45 UTC, merged